package fr.univrouen.stb23v1.model.entities;

import jakarta.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


@XmlRootElement(name = "features")
@XmlAccessorType(XmlAccessType.FIELD)
public class Features {
    /**
     * Autogenerated id.
     */
    @XmlTransient
    private Integer id;


    @XmlElement(name = "feature")
    private List<Feature> feature;

    // Getters and setters
    public List<Feature> getFeature() {
        return feature;
    }

    public void setFeature(List<Feature> feature) {
        this.feature = feature;
    }

    // Constructors
    public Features() {
        this.feature = new ArrayList<Feature>();
    }

    public Features(ArrayList<Feature> feature) {
        this.feature = feature;
    }

    // Methods
    public void addFeature(Feature feature) {
        this.feature.add(feature);
    }

    public void removeFeature(Feature feature) {
        this.feature.remove(feature);
    }

    public Feature getFeature(int index) {
        return this.feature.get(index);
    }

    public int size() {
        return this.feature.size();
    }

    public boolean isEmpty() {
        return this.feature.isEmpty();
    }

    public boolean contains(Feature feature) {
        return this.feature.contains(feature);
    }

    public void clear() {
        this.feature.clear();
    }

    // Methods
    public String toString() {
        String str = "Features{\n";
        for (Feature feature : this.feature) {
            str += feature.toString() + "\n";
        }
        str += "}";
        return str;
    }


}
