package fr.univrouen.stb23v1.model.entities;

import jakarta.xml.bind.annotation.*;

@XmlRootElement(name = "feature")
@XmlAccessorType(XmlAccessType.FIELD)
public class Feature {

  /**
   * Autogenerated id.
   */
  @XmlTransient
  private Integer id;

  @XmlElement(name = "description")
  private String description;

  @XmlElement(name = "priority")
  private Integer priority;

  @XmlElement(name = "delivery")
  private String delivery;

  @XmlElement(name = "comment")
  private String comment;

  @XmlAttribute(name = "name")
  private String name;
  
  @XmlAttribute(name = "section")
  private Integer section;
  
  @XmlAttribute(name = "number")
  private Integer number;

  // Getters and setters

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public int getPriority() {
    return priority;
  }

  public void setPriority(int priority) {
    this.priority = priority;
  }

  public String getDelivery() {
    return delivery;
  }

  public void setDelivery(String delivery) {
    this.delivery = delivery;
  }

  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public int getSection() {
    return section;
  }

  public void setSection(int section) {
    this.section = section;
  }

  public int getNumber() {
    return number;
  }

  public void setNumber(int number) {
    this.number = number;
  }

  //Constructors
  public Feature() {
  }

  public Feature(String description, int priority, String delivery, String comment) {
    this.description = description;
    this.priority = priority;
    this.delivery = delivery;
    this.comment = comment;
  }

  //Methods
  @Override
  public String toString() {
    return "Feature{" +
            "description='" + description + '\'' +
            ", priority=" + priority +
            ", delivery='" + delivery + '\'' +
            ", comment='" + comment + '\'' +
            '}';
  }
}
